//! Every redaction the corpus can ask for, pinned byte for byte.
//!
//! # What this is for
//!
//! #191 moves redaction's policy — about 4,400 lines of it — off the native qpdf handle and onto
//! a trait both platforms implement. ADR 0029's #191 amendment makes the move land **alone and
//! with no behaviour change**, because a refactor with nothing new to show for itself is exactly
//! where a behaviour change hides. "The native suites stay green" is necessary and it is not the
//! claim: those suites assert properties, and a rewrite that keeps every property and changes
//! the bytes passes all of them.
//!
//! So this pins the **outcome itself**, for every case below:
//!
//! - `Ok` — the sha256 of the emitted document, and of the report beside it;
//! - `Err` — the error, in full. Not just the rule in brackets: the same rule reached with a
//!   different message is a different route, which is ADR 0016's lesson about `Stage`.
//!
//! The file was blessed from `main` before the move began, so it is the "before", committed.
//! CI then checks the "after" on the exact commit being merged, which is a stronger proof than a
//! local comparison nobody else can rerun. PR 2 of #191 holds the web implementation to it too.
//!
//! # What it runs
//!
//! Every PDF in the redaction corpus, the conformance fixtures and `tests/damaged/`, through the
//! public operation `burrow_ops::redact::page` — verification included — with:
//!
//! - **regions**: the manifest's own region for the fixture if it declares one, `pdfbuild.REGION`
//!   (which draws every hand-built fixture's canary), the whole page, and a horizontal band;
//! - **pages**: the first, the last, and one past the end — the refusal for that is an outcome
//!   too;
//! - **covered pages**: the page alone, and for a multi-page document every page, which is what
//!   decides whether a font may be cut.
//!
//! Under a clock that never moves, so no outcome depends on how fast the machine is.
//!
//! # What it cannot say
//!
//! It pins what the corpus **does**, not what it should do: a leak that exists today is pinned as
//! faithfully as a correct redaction. That is the right instrument for a refactor and the wrong
//! one for a fix — a change that is *meant* to alter an outcome re-blesses, and the diff of this
//! file is then the reviewable list of what changed.
//!
//! # The fixtures are recorded too
//!
//! `tests/redaction/generated/` is gitignored and regenerated by
//! `tools/check-redaction-corpus.sh`. Each input's sha256 is recorded beside its outcomes, and a
//! document whose bytes differ from the recorded ones **fails by name** rather than being
//! skipped: an output that changed because its input changed is not a finding about the code, and
//! a gate that quietly left it out would be examining less than it reports.
//!
//! # Blessing
//!
//! ```text
//! BURROW_BLESS_REDACTION_OUTCOMES=1 cargo test -p burrow-ops --features native-engines \
//!     --test redaction_outcomes
//! ```

#![cfg(all(feature = "native-engines", target_os = "linux"))]
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::print_stdout,
    reason = "a test reading committed fixtures it lists from disk; the workspace lints are for \
              attacker-controlled input in library code, where they stay denied"
)]

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use burrow_engines::pdfsyntax::region::Region;
use burrow_engines::qpdf::Qpdf;
use burrow_engines::{OpenOptions, PageRotator};
use burrow_types::{Clock, Limits, ManualClock};
use sha2::{Digest, Sha256};

/// Where every document comes from, relative to this crate. Read in full; none is optional.
const DIRECTORIES: &[&str] = &[
    "../../tests/redaction/fixtures",
    "../../tests/redaction/generated",
    "../../tests/conformance/fixtures",
    "../../tests/damaged",
];

/// The recorded outcomes.
const GOLDEN: &str = "../../tests/redaction/outcomes.tsv";

/// The manifest, for the regions it declares.
const MANIFEST: &str = "../../tests/redaction/manifest.toml";

/// `tools/pdfbuild.py`'s `REGION`, `(30, 88, 370, 132)` in PDF space on a 200-point-high page,
/// converted to the display coordinates the operation takes: `(x0, H - y1, x1 - x0, y1 - y0)`.
const PDFBUILD_REGION: Region = Region {
    left: 30.0,
    top: 68.0,
    width: 340.0,
    height: 44.0,
};

/// Larger than any page in the corpus.
const WHOLE_PAGE: Region = Region {
    left: 0.0,
    top: 0.0,
    width: 5000.0,
    height: 5000.0,
};

/// A band across the middle of a letter-sized page, which catches text the other two do not.
const BAND: Region = Region {
    left: 0.0,
    top: 300.0,
    width: 5000.0,
    height: 120.0,
};

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).to_path_buf()
}

fn hex(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(64);
    for byte in Sha256::digest(bytes) {
        let _ = write!(out, "{byte:02x}");
    }
    out
}

fn options() -> OpenOptions<'static> {
    OpenOptions::new(
        Limits::default(),
        Arc::new(ManualClock::new(0)) as Arc<dyn Clock>,
    )
}

/// Every document, as `(path relative to the repository, bytes)`, sorted.
fn documents() -> Vec<(String, Vec<u8>)> {
    let mut out = Vec::new();
    for directory in DIRECTORIES {
        let path = root().join(directory);
        let mut entries: Vec<PathBuf> = std::fs::read_dir(&path)
            .unwrap_or_else(|error| panic!("{}: {error}", path.display()))
            .filter_map(|entry| entry.ok())
            .map(|entry| entry.path())
            .filter(|path| {
                path.extension()
                    .is_some_and(|extension| extension == "pdf" || extension == "bin")
            })
            .collect();
        entries.sort();
        assert!(
            !entries.is_empty(),
            "{} holds no documents; run tools/check-redaction-corpus.sh first",
            path.display()
        );
        for file in entries {
            let name = format!(
                "{}/{}",
                directory.trim_start_matches("../../"),
                file.file_name().unwrap().to_string_lossy()
            );
            out.push((name, std::fs::read(&file).unwrap()));
        }
    }
    out
}

/// The manifest's `region` for each `file`, keyed by the path this test names documents by.
///
/// Parsed by hand rather than by adding a TOML dependency to a test: only two keys are read, and
/// the count of `region` lines is checked against what was found so a format change fails here
/// instead of silently yielding fewer regions.
fn manifest_regions() -> BTreeMap<String, Region> {
    let text = std::fs::read_to_string(root().join(MANIFEST)).unwrap();
    let mut out = BTreeMap::new();
    let mut region: Option<Region> = None;
    let mut declared = 0usize;
    // A KEY IS WHATEVER PRECEDES ITS `=`, however it is spaced. The first version matched the
    // exact prefix `region = [`, so a `region=[...]` line would have been neither parsed nor
    // counted, and both count assertions below would have passed over it (code review of #191).
    let value_of = |line: &str, key: &str| -> Option<String> {
        let (name, value) = line.split_once('=')?;
        (name.trim() == key).then(|| value.trim().to_owned())
    };
    for line in text.lines() {
        let line = line.trim();
        if line == "[[fixture]]" {
            region = None;
        } else if let Some(value) = value_of(line, "region") {
            declared += 1;
            let Some(inner) = value.strip_prefix('[').and_then(|v| v.strip_suffix(']')) else {
                panic!("a manifest region that is not a one-line array: {line}");
            };
            let numbers: Vec<f64> = inner
                .split(',')
                .map(|n| n.trim().parse().unwrap())
                .collect();
            let [left, top, width, height] = numbers[..] else {
                panic!("a manifest region that is not four numbers: {line}");
            };
            region = Some(Region {
                left,
                top,
                width,
                height,
            });
        } else if let Some(file) = value_of(line, "file")
            && let Some(found) = region.take()
        {
            out.insert(format!("tests/redaction/{}", file.trim_matches('"')), found);
        }
    }
    // Every `region` line precedes its `file` in the manifest; one that did not would be dropped
    // above, and this is what says so.
    assert_eq!(
        out.len(),
        declared,
        "the manifest declares {declared} regions and {} were attributed to a file",
        out.len()
    );
    out
}

/// One case: which page, which pages the operation covers, and which region.
struct Case {
    page: usize,
    covered: BTreeSet<usize>,
    label: &'static str,
    region: Region,
}

fn cases(pages: Option<usize>, manifest: Option<Region>) -> Vec<Case> {
    let mut regions: Vec<(&'static str, Region)> = Vec::new();
    if let Some(region) = manifest {
        regions.push(("manifest", region));
    }
    regions.push(("pdfbuild", PDFBUILD_REGION));
    regions.push(("whole", WHOLE_PAGE));
    regions.push(("band", BAND));

    let mut targets: BTreeSet<usize> = BTreeSet::from([0]);
    if let Some(count) = pages
        && count > 0
    {
        targets.insert(count - 1);
    }
    let mut out = Vec::new();
    // ONE PAST THE END, ONCE. The refusal comes before any region is read, so one region says
    // everything four would.
    if let Some(count) = pages {
        out.push(Case {
            page: count,
            covered: BTreeSet::from([count]),
            label: "whole",
            region: WHOLE_PAGE,
        });
    }
    for page in &targets {
        for (label, region) in &regions {
            out.push(Case {
                page: *page,
                covered: BTreeSet::from([*page]),
                label,
                region: *region,
            });
        }
    }
    if let Some(count) = pages
        && count > 1
    {
        out.push(Case {
            page: 0,
            covered: (0..count).collect(),
            label: "whole",
            region: WHOLE_PAGE,
        });
    }
    out
}

fn covered_label(covered: &BTreeSet<usize>) -> String {
    let all: Vec<String> = covered.iter().map(ToString::to_string).collect();
    all.join(",")
}

/// Run every case, as the lines the golden file holds.
fn measure() -> (Vec<String>, usize) {
    let manifest = manifest_regions();
    let documents = documents();
    let mut lines = Vec::new();
    let mut matched_regions = 0usize;
    for (name, bytes) in &documents {
        lines.push(format!("INPUT\t{name}\t{}", hex(bytes)));
        let pages = Qpdf
            .open(bytes.clone().into_boxed_slice(), &options())
            .and_then(|source| Qpdf.pages(&source))
            .ok()
            .and_then(|count| usize::try_from(count).ok());
        let region = manifest.get(name).copied();
        matched_regions += usize::from(region.is_some());
        for case in cases(pages, region) {
            let outcome = match burrow_ops::redact::page(
                &Qpdf,
                bytes,
                case.page,
                &case.covered,
                case.region,
                &options(),
            ) {
                Ok(done) => format!(
                    "OK {} report {}",
                    hex(&done.document),
                    hex(format!("{:?}", done.report).as_bytes())
                ),
                Err(error) => format!("ERR {}", format!("{error:?}").replace(['\n', '\t'], " ")),
            };
            lines.push(format!(
                "CASE\t{name}\t{}\t{}\t{}\t{outcome}",
                case.page,
                covered_label(&case.covered),
                case.label
            ));
        }
    }
    // EVERY REGION THE MANIFEST DECLARES WAS USED, so a renamed fixture cannot quietly fall back
    // to the default region and still match its old outcome by accident.
    assert_eq!(
        matched_regions,
        manifest.len(),
        "the manifest declares {} regions and {matched_regions} matched a document",
        manifest.len()
    );
    (lines, documents.len())
}

/// Every way `computed` differs from `recorded`, named.
fn differences(recorded: &[String], computed: &[String]) -> Vec<String> {
    let key = |line: &String| -> String {
        let fields: Vec<&str> = line.split('\t').collect();
        match fields.first() {
            Some(&"INPUT") => fields[..2].join("\t"),
            _ => fields[..fields.len().saturating_sub(1)].join("\t"),
        }
    };
    let before: BTreeMap<String, &String> = recorded.iter().map(|l| (key(l), l)).collect();
    let after: BTreeMap<String, &String> = computed.iter().map(|l| (key(l), l)).collect();
    let mut out = Vec::new();
    for (k, line) in &before {
        match after.get(k) {
            None => out.push(format!("missing now: {line}")),
            Some(now) if now != line => {
                out.push(format!("changed:\n    was {line}\n    now {now}"));
            }
            Some(_) => {}
        }
    }
    for (k, line) in &after {
        if !before.contains_key(k) {
            out.push(format!("not recorded: {line}"));
        }
    }
    out
}

#[test]
fn every_redaction_outcome_in_the_corpus_is_the_recorded_one() {
    let (computed, documents) = measure();
    let path = root().join(GOLDEN);

    // BLESSING IS ASKED FOR BY NAME, AND NEVER IN CI. `var_os(..).is_some()` blessed on `=0` or an
    // empty value too, and a bless returns before any assertion runs, so a CI job that happened to
    // set it would have rewritten the golden and passed (code review of #191).
    let bless = std::env::var("BURROW_BLESS_REDACTION_OUTCOMES").is_ok_and(|value| value == "1");
    if bless {
        assert!(
            std::env::var_os("CI").is_none(),
            "refusing to bless the redaction outcomes in CI: the golden is the thing CI checks"
        );
        let mut text = String::from(
            "# Every redaction outcome in the corpus, byte for byte. Written by\n\
             # core/burrow-ops/tests/redaction_outcomes.rs under BURROW_BLESS_REDACTION_OUTCOMES=1;\n\
             # see its header for what each line means and when to re-bless.\n",
        );
        for line in &computed {
            text.push_str(line);
            text.push('\n');
        }
        std::fs::write(&path, text).unwrap();
        println!(
            "blessed {} lines over {documents} documents",
            computed.len()
        );
        return;
    }

    let recorded: Vec<String> = std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("{}: {error}", path.display()))
        .lines()
        .filter(|line| !line.starts_with('#') && !line.is_empty())
        .map(str::to_owned)
        .collect();

    // THE COUNTS, AND WHAT THEY SHOULD BE. The documents are the directory listing; the cases are
    // what the golden file recorded. Both printed, so a run over fewer reads as fewer.
    let cases = computed.iter().filter(|l| l.starts_with("CASE\t")).count();
    let redacted = computed.iter().filter(|l| l.contains("\tOK ")).count();
    let refused = computed.iter().filter(|l| l.contains("\tERR ")).count();
    let recorded_cases = recorded.iter().filter(|l| l.starts_with("CASE\t")).count();
    let recorded_inputs = recorded.iter().filter(|l| l.starts_with("INPUT\t")).count();
    println!(
        "redaction outcomes: {cases} cases over {documents} documents ({redacted} redacted, \
         {refused} refused); recorded {recorded_cases} cases over {recorded_inputs} documents"
    );
    assert_eq!(
        redacted + refused,
        cases,
        "a case that is neither OK nor ERR"
    );

    let found = differences(&recorded, &computed);
    assert!(
        found.is_empty(),
        "{} of {} recorded lines differ. An INPUT line differing means the fixture changed, not \
         the code; anything else is a behaviour change. Re-bless only if it is meant:\n{}",
        found.len(),
        recorded.len(),
        found.join("\n")
    );
    assert_eq!(recorded_inputs, documents);
    assert_eq!(recorded_cases, cases);
}

/// The comparison sees each kind of difference, so a clean run is a measurement.
#[test]
fn the_comparison_names_every_kind_of_difference() {
    let recorded = vec![
        "INPUT\ta.pdf\t00".to_owned(),
        "CASE\ta.pdf\t0\t0\twhole\tOK 11 report 22".to_owned(),
        "CASE\ta.pdf\t1\t1\twhole\tERR Malformed(\"pdf redaction [x]: y\")".to_owned(),
    ];
    assert!(differences(&recorded, &recorded).is_empty());

    // A different output.
    let mut changed = recorded.clone();
    changed[1] = "CASE\ta.pdf\t0\t0\twhole\tOK 12 report 22".to_owned();
    assert_eq!(differences(&recorded, &changed).len(), 1);

    // The same rule with a different message is a different outcome.
    let mut reworded = recorded.clone();
    reworded[2] = "CASE\ta.pdf\t1\t1\twhole\tERR Malformed(\"pdf redaction [x]: z\")".to_owned();
    assert_eq!(differences(&recorded, &reworded).len(), 1);

    // A refusal that became a redaction.
    let mut flipped = recorded.clone();
    flipped[2] = "CASE\ta.pdf\t1\t1\twhole\tOK 33 report 22".to_owned();
    assert_eq!(differences(&recorded, &flipped).len(), 1);

    // A different input.
    let mut refixtured = recorded.clone();
    refixtured[0] = "INPUT\ta.pdf\t01".to_owned();
    assert_eq!(differences(&recorded, &refixtured).len(), 1);

    // A case gone, and a case new.
    assert_eq!(differences(&recorded, &recorded[..2]).len(), 1);
    let mut grown = recorded.clone();
    grown.push("CASE\ta.pdf\t0\t0\tband\tOK 44 report 22".to_owned());
    assert_eq!(differences(&recorded, &grown).len(), 1);
}
