#!/usr/bin/env python3
"""Generate the cross-reference decompression bomb used by the memory limit test.

    python3 tools/make-xref-bomb.py tests/conformance/fixtures/xref-bomb.pdf

A small, structurally valid PDF whose cross-reference **stream** declares twenty million
entries. The stream's uncompressed form is `Size * sum(W)` = 20,000,000 * 17 = 340 MB of
mostly zeros, which deflates to a few hundred kilobytes. PDFium has to inflate it to parse
the file at all, and ends up resident in roughly 1.2 GB.

Why this file exists
--------------------
`burrow-engines`' size-based memory pre-check is a function of the input's *length* and
nothing else, so it predicts about 16 MB here and lets the file straight through -- an
amplification of roughly 3,900x that no tuning of that estimate could ever catch, because
the declared size is not present in the byte count. The measured post-open check
(`pdfium::estimate::check_measured_memory`) is what turns this from `Ok(1 page)` into
`LimitExceeded`, and `core/burrow-engines/tests/limits.rs` is what proves it stays that
way.

Why this generator is Python and not Rust
-----------------------------------------
Every other fixture is generated by `cargo run -p burrow-engines --example
make-conformance-fixtures`, which is the better arrangement. This one needs a real deflate
compressor: the whole point is a large expansion ratio, and a hand-rolled fixed-Huffman
encoder in the test support would produce a file several times larger for no benefit.
Python ships zlib, so the generator is fifteen lines. The output is committed, and this
script is committed beside it so the file is reproducible rather than opaque.

Deterministic: the same input always produces byte-identical output, so the digest
recorded in `tests/conformance/PROVENANCE.md` is stable.
"""

import sys
import zlib

# 20,000,000 entries of 1 + 8 + 8 bytes. Large enough to force a multi-hundred-megabyte
# allocation; small enough that generating it here takes under a second.
SIZE = 20_000_000
W = (1, 8, 8)


def build() -> bytes:
    out = bytearray()
    out += b"%PDF-1.5\n"
    out += b"1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n"
    out += b"2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n"
    out += b"3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 10 10] >>\nendobj\n"

    xref_offset = len(out)

    # The table itself: all zeros. A type-0 (free) entry for every object. It is not a
    # useful cross-reference table and does not need to be -- PDFium allocates and inflates
    # it before it can discover that.
    table = bytes(SIZE * sum(W))
    # Level 9 so the committed file is as small as the bomb allows.
    stream = zlib.compress(table, 9)

    out += (
        f"4 0 obj\n<< /Type /XRef /Size {SIZE} /W [{W[0]} {W[1]} {W[2]}] "
        f"/Root 1 0 R /Filter /FlateDecode /Length {len(stream)} >>\nstream\n"
    ).encode("ascii")
    out += stream
    out += b"\nendstream\nendobj\n"
    out += f"startxref\n{xref_offset}\n%%EOF\n".encode("ascii")
    return bytes(out)


def main() -> int:
    if len(sys.argv) != 2:
        print(f"usage: {sys.argv[0]} <output.pdf>", file=sys.stderr)
        return 2
    data = build()
    with open(sys.argv[1], "wb") as handle:
        handle.write(data)
    ratio = (SIZE * sum(W)) / len(data)
    print(f"wrote {sys.argv[1]}: {len(data)} bytes, expands ~{ratio:.0f}x on parse")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
